.PHONY: echoingaudiopeer micliveaudio

echoingaudiopeer:
	go run echoingaudiopeer/main.go  -configFilePath echoingaudiopeer/config.yaml

micliveaudio:
	go run micliveaudio/main.go  -configFilePath micliveaudio/config.yaml

app:
	go run rtaudioapp/main.go  -configFilePath rtaudioapp/config.yaml
