package networking

import (
	"github.com/google/uuid"
	"github.com/pion/webrtc/v4"
)

// Holds all relevant information for the signalling server to route
// a request from offerer to answerer across the network
// in order to facilitate a new p2p connection between the two.
type SignallingOffer struct {
	// The public IP address of the peer, including port number.
	// Should be discovered by the
	RemoteEndpoint string

	// The UUID of the offer as generated by the offering client
	// Will be used across several logs for correlation
	OfferUUID uuid.UUID

	WebRTCSessionDescription webrtc.SessionDescription
}

// Holds information from answering peer to offering peer
type SignallingAnswer struct {
	// The same UUID as given by the offering client
	OfferUUID uuid.UUID

	WebRTCSessionDescription webrtc.SessionDescription
}
