.PHONY: answeringpeer offeringpeer

answeringpeer:
	go run -tags=nolibopusfile answeringpeer/main.go -configFilePath answeringpeer/config.yaml

offeringpeer:
	go run -tags=nolibopusfile offeringpeer/main.go -audioFile ./assets/media.wav