.PHONY: answeringpeer offeringpeer

answeringpeer:
	go run answeringpeer/main.go -configFilePath answeringpeer/config.yaml

offeringpeer:
	go run offeringpeer/main.go -configFilePath offeringpeer/config.yaml -audioFile assets/media.wav
